package bf;
public class test{
public static char mem[] = new char[0xffff];
public static short memPtr=0;
public static void main(String[] args){
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
while(mem[0xffff & memPtr]!=0){
mem[0xffff & memPtr]--;
memPtr++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
memPtr--;
}
memPtr++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
memPtr--;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
System.out.print(mem[memPtr]);
memPtr++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
mem[0xffff & memPtr]++;
System.out.print(mem[memPtr]);
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
System.out.print(mem[memPtr]);
memPtr--;
System.out.print(mem[memPtr]);
memPtr++;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
mem[0xffff & memPtr]--;
System.out.print(mem[memPtr]);
}
}